export { default as Footer } from './Footer'
export { default } from './Home'
export { default as Meta } from './Meta'
export { default as Nav } from './Nav'
export { default as SectionAbout } from './SectionAbout'
export { default as SectionContact } from './SectionContact'
export { default as SectionHome } from './SectionHome'
